version: '3.9'
services:
  main:
    container_name: main
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 4000:4000
    command: npm run dev
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: postgres
    image: postgres:14
    restart: always
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres:
