version: '3.9'

services:
  server:
    build: .
    ports:
      - '5000:5000'
    depends_on:
      - db
  db:
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: 'imageimageimageimage123'
      POSTGRES_USER: 'docker'
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
